num_vector <- c(1,2,3,4,5)
fac_vector <- as.factor(c('A','B','C','A','B'))
log_vector <- c(TRUE,FALSE,FALSE,TRUE,TRUE)
num_variance <- var(num_vector)
cat('Variance of the numwerical vector = ',num_variance,'\n')
data_matrix <- matrix(c(num_vector,fac_vector,log_vector),nrow = length(num_vector),byrow = FALSE)
cov_matrix <- cov(data_matrix)
cat('Covariance = \n')
print(cov_matrix)
cor_matrix <- cor(data_matrix)
cat('Correlation = \n')
print(cor_matrix)