library(e1071)
data("iris")
set.seed(123)
svm_model = svm(Species ~ ., data=iris, kernel='radial')
predictions = predict(svm_model, iris)
accuracy = mean(predictions == iris$Species)
cat('Accuracy:',accuracy*100,'%','\n')
print('Confusion Matrix:')
conf_matrix = table(iris$Species, predictions)
print(conf_matrix)